name:                sml-base-functor
version:             0.1.0.0
github:              "githubuser/sml-base-functor"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sml-base-functor#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- recursion-schemes
- parser-combinators
- prettyprinter
- pretty-show

library:
  source-dirs: src

executables:
  sml-base-functor-exe:
    main:                Main.hs
    source-dirs:         app
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - sml-base-functor

tests:
  sml-base-functor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sml-base-functor
